name = "Haskell"
entrypoint = "main.hs"

[install]
depends = [
  "c"
]

packages = [
  "ghc"
]

[[execute]]
compile = "ghc -o main main.hs"
run = "./main"

[[execute.test]]
code = """
main = putStrLn "hello"
"""
output = "hello\n"
