name = "JavaScript"
entrypoint = "index.js"

[install]
packages = [
  "npm"
]

setup = [
  "npm i -g prettier@2.1.2"
]

[[execute]]
name = "Node.js"
run = "node index.js"

[[execute.test]]
code = """
console.log("hello");
"""
output = "hello\n"

[format]
command = "prettier index.js"
