name = "Python"
entrypoint = "main.py"

[install]
depends = [
  "c"
]

packages = [
  "python3-dev",
  "python2-dev",
  "py3-pip"
]

setup = [
  "pip install black"
]

[[execute]]
name = "Python 3"
run = "python3 main.py"

[[execute.test]]
code = """
print('hello')
"""
output = "hello\n"

[[execute]]
name = "Python 2"
run = "python2 main.py"

[[execute.test]]
code = """
print 'hello'
"""
output = "hello\n"

[format]
command = "black -q - < main.py"
