name = "C"
entrypoint = "main.c"

[install]
packages = [
  "gcc",
  "musl-dev"
]

[[execute]]
compile = "gcc -o main main.c"
run = "./main"

[[execute.test]]
code = """
#include <stdio.h>

int main() {
  printf("hello");
  return 0;
}
"""
output = "hello"
