name = "Go"
entrypoint = "main.go"

[install]
packages = [
  "go"
]

[[execute]]
compile = "go build -o main main.go"
run = "./main"

[[execute.test]]
code = """
package main

import "fmt"

func main() {
    fmt.Println("hello")
}
"""
output = "hello\n"

[format]
command = "gofmt main.go"
