name = "JavaScript"
entrypoint = "index.js"

[install]
packages = [
    "npm"
]

setup = [
    "npm i -g prettier@2.1.2"
]

[[execute]]
run = [
    "node",
    "index.js"
]

[format]
command = [
    "prettier",
    "index.js"
]
