name = "Python"
entrypoint = "main.py"

[install]
packages = [
  "python3",
  "python2"
]

[[execute]]
name = "Python 3"
run = [
  "python3",
  "main.py"
]

[[execute]]
name = "Python 2"
run = [
  "python2",
  "main.py"
]
