name = "Rust"
entrypoint = "main.rs"

[install]
packages = [
  "rust"
]

[[execute]]
compile = "rustc -o main main.rs"
run = "./main"

[[execute.test]]
code = """
fn main() {
  println!("hello");
}
"""
output = "hello\n"
