name = "TypeScript"
entrypoint = "index.ts"

[install]
depends = [
  "javascript"
]

setup = [
  "npm i -g typescript@4.0.5"
]

[[execute]]
name = "Node.js"

compile = [
  "tsc",
  "index.ts"
]

run = [
  "node",
  "index.js"
]

[format]
command = [
  "prettier",
  "index.ts"
]
