name = "TypeScript"
entrypoint = "index.ts"

[install]
packages = [
    "npm"
]

setup = [
    "npm i -g prettier@2.1.2 typescript@4.0.5"
]

[[execute]]
compile = [
    "tsc",
    "index.ts"
]

run = [
    "node",
    "index.js"
]

[format]
command = [
    "prettier",
    "index.ts"
]
